[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$Slug,
    [string]$Root = ""
)

$ErrorActionPreference = "Stop"
if ([string]::IsNullOrWhiteSpace($Root)) {
    $Root = Split-Path -Parent $PSScriptRoot
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )

    $parent = Split-Path -Parent $Path
    if ($parent) {
        New-Item -ItemType Directory -Force -Path $parent | Out-Null
    }
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

function Assert-ContainedPath {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Container
    )

    $fullPath = [System.IO.Path]::GetFullPath($Path)
    $fullContainer = ([System.IO.Path]::GetFullPath($Container)).TrimEnd([System.IO.Path]::DirectorySeparatorChar) + [System.IO.Path]::DirectorySeparatorChar
    if (-not $fullPath.StartsWith($fullContainer, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Resolved path '$fullPath' escapes '$fullContainer'."
    }
    return $fullPath
}

function Add-Template {
    param(
        [Parameter(Mandatory = $true)][System.Collections.IDictionary]$Files,
        [Parameter(Mandatory = $true)][string]$RelativePath,
        [Parameter(Mandatory = $true)][string]$Content
    )
    $Files[$RelativePath] = $Content.TrimStart("`r", "`n") + "`n"
}

try {
    if ($Slug -cnotmatch '^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$') {
        throw "Slug must be lower-kebab-case, start with a letter, and contain only letters, digits, and single hyphens."
    }

    $repoRoot = [System.IO.Path]::GetFullPath($Root)
    $gamesRoot = Assert-ContainedPath -Path (Join-Path $repoRoot "games") -Container $repoRoot
    $settingsPath = Join-Path $repoRoot "settings.gradle.kts"
    if (-not (Test-Path -LiteralPath $settingsPath -PathType Leaf)) {
        throw "settings.gradle.kts was not found under '$repoRoot'."
    }

    $gamePath = Assert-ContainedPath -Path (Join-Path $gamesRoot $Slug) -Container $gamesRoot
    $stagePath = Assert-ContainedPath -Path (Join-Path $gamesRoot ("." + $Slug + ".scaffold")) -Container $gamesRoot
    if (Test-Path -LiteralPath $gamePath) {
        throw "Refusing to overwrite existing game '$Slug' at '$gamePath'."
    }
    if (Test-Path -LiteralPath $stagePath) {
        throw "Refusing to reuse existing staging directory '$stagePath'; archive it manually before retrying."
    }

    $settingsText = [System.IO.File]::ReadAllText($settingsPath)
    $modulePath = ":games:$Slug"
    $includeLine = 'include("' + $modulePath + '")'
    $projectLine = 'project("' + $modulePath + '").projectDir = file("games/' + $Slug + '")'
    if ($settingsText.Contains($includeLine) -or $settingsText.Contains($projectLine)) {
        throw "settings.gradle.kts already contains wiring for '$modulePath'."
    }

    $packageName = $Slug.Replace('-', '_')
    $packPath = "content/$Slug"
    $files = [ordered]@{}

    Add-Template $files "build.gradle.kts" @'
plugins {
    `java-library`
    alias(libs.plugins.kotlin.jvm)
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    api(project(":engine-core"))
    api(project(":engine-content"))
    testImplementation(libs.kotlin.test.junit5)
    testImplementation(libs.junit.jupiter)
}

tasks.test {
    useJUnitPlatform()
}
'@

    Add-Template $files "README.md" @'
# __SLUG__

This is a deterministic starter game generated by `scripts/me-new-game.ps1`.

## Contents

- External starter content pack under `games/__SLUG__/content/__SLUG__`.
- Canonical JVM replay scenario under `src/test`.
- Spec bundle under `spec/` following `docs/GAME_SPEC_PIPELINE.md`.

Run the module tests with:

```powershell
.\gradlew.bat :games:__SLUG__:test
```
'@

    Add-Template $files "replay-scenario.properties" @'
module=:games:__SLUG__
testTask=:games:__SLUG__:test
testClass=dev.myengine.games.__PACKAGE__.CanonicalScenarioTest
expectedHash=b8a9908f5d7a8281
'@

    Add-Template $files "src/main/kotlin/dev/myengine/games/__PACKAGE__/CanonicalScenario.kt" @'
package dev.myengine.games.__PACKAGE__

import dev.myengine.core.SeededRandom
import dev.myengine.core.stableHashOf

data class CanonicalScenarioResult(
    val trajectory: List<String>,
    val finalHash: String,
)

object CanonicalScenario {
    private const val TICKS = 12
    private const val DEFAULT_SEED = 7L

    fun run(seed: Long = DEFAULT_SEED): CanonicalScenarioResult {
        val random = SeededRandom(seed)
        val trajectory = buildList {
            repeat(TICKS) { tick ->
                val signal = random.nextInt(100)
                add(stableHashOf {
                    add("canonical")
                    add(tick)
                    add(signal)
                })
            }
        }
        val finalHash = stableHashOf {
            add("canonical")
            add(seed)
            trajectory.forEach(::add)
        }
        return CanonicalScenarioResult(trajectory, finalHash)
    }
}
'@

    Add-Template $files "src/test/kotlin/dev/myengine/games/__PACKAGE__/CanonicalScenarioTest.kt" @'
package dev.myengine.games.__PACKAGE__

import kotlin.test.Test
import kotlin.test.assertEquals

class CanonicalScenarioTest {
    @Test
    fun sameSeedProducesTheGoldenReplayTrajectory() {
        val first = CanonicalScenario.run()
        val second = CanonicalScenario.run()

        assertEquals(first.trajectory, second.trajectory)
        assertEquals(
            listOf(
                "9b5648d071b592b4",
                "83d051386320d17c",
                "9d4507ee47ae2a14",
                "42c47ac35dc47f5d",
                "1114d42ebe773f7e",
                "32b3529c4b8a470e",
                "76715849c69bf27a",
                "1bf0cb1edcb247c3",
                "e3c3b4a82c06caab",
                "c5c04d2e0c13cc3a",
                "b30b6da277b5d67c",
                "129f7a221aa7724e",
            ),
            first.trajectory,
        )
        assertEquals("b8a9908f5d7a8281", first.finalHash)
    }
}
'@

    Add-Template $files "$packPath/manifest.properties" @'
id=__SLUG__
version=0.1.0
schemaVersion=1
engineMin=0.0.1
engineMax=0.1.x
locales=en
dependencies=
'@
    Add-Template $files "$packPath/tiles.properties" @'
floor.buildable=true
floor.blocksMovement=false
wall.buildable=false
wall.blocksMovement=true
core.buildable=false
core.blocksMovement=false
core.isCore=true
resource.buildable=false
resource.blocksMovement=false
'@
    Add-Template $files "$packPath/resources.properties" @'
bolt.displayKey=resource.bolt
'@
    Add-Template $files "$packPath/recipes.properties" @'
generator.outputResource=bolt
generator.outputAmount=1
generator.durationTicks=3
'@
    Add-Template $files "$packPath/towers.properties" @'
basic.displayKey=tower.basic
basic.range=3
basic.damage=1
basic.cooldownTicks=2
basic.costResource=bolt
basic.costAmount=2
basic.sellRefundRatio=0.5
basic.targetingMode=nearest
'@
    Add-Template $files "$packPath/enemies.properties" @'
scout.health=3
scout.speedTilesPerTick=1
scout.rewardResource=bolt
scout.rewardAmount=1
scout.coreDamage=1
'@
    Add-Template $files "$packPath/waves.properties" @'
wave1.startTick=2
wave1.spawns=scout:2
'@
    Add-Template $files "$packPath/incidents.properties" @'
spark.minThreat=0
spark.maxThreat=5
spark.weight=1
'@
    Add-Template $files "$packPath/strings.properties" @'
resource.bolt=Bolt
tower.basic=Basic tower
hud.resources=Resources
hud.wave=Wave
hud.nextWave=Next wave
hud.coreHealth=Core
hud.build=Build
hud.upgrade=Upgrade
hud.damage=Damage
hud.kills=Kills
hud.tier=Tier
building.marker=Marker
'@
    Add-Template $files "$packPath/maps.json" @'
{
  "maps": [
    {
      "id": "__SLUG__-canonical",
      "width": 8,
      "height": 8,
      "terrainRows": [
        "########",
        "#......#",
        "#.R....#",
        "#......#",
        "#......#",
        "#......#",
        "#.....C#",
        "########"
      ],
      "terrainMapping": {
        ".": { "tile": "floor" },
        "#": { "tile": "wall" },
        "C": { "tile": "core" },
        "R": { "tile": "resource", "resource": { "id": "bolt", "amount": 100 } }
      },
      "spawns": [
        { "id": "entry", "x": 1, "y": 1 }
      ],
      "core": { "x": 6, "y": 6 },
      "terminalRules": {
        "winCondition": "finite_waves"
      }
    }
  ]
}
'@

    Add-Template $files "spec/00_manifest.yaml" @'
id: __SLUG__
title: __SLUG__ starter game
version: 0.1.0
status: draft
'@
    Add-Template $files "spec/product-brief.md" "# __SLUG__`n`nStarter product brief. Replace this generated placeholder during Gate 1."
    Add-Template $files "spec/requirements.md" @'
# Requirements

- FR-001: The starter game exposes a deterministic canonical scenario.
'@
    Add-Template $files "spec/user-stories.md" @'
# User stories

- US-001: As a developer, I can run the starter scenario and receive a stable replay hash.
'@
    Add-Template $files "spec/acceptance/AC-001.feature" @'
Feature: __SLUG__ starter replay

  Scenario: Canonical scenario is deterministic
    Given the generated starter project
    When the canonical scenario runs with seed 7
    Then the replay hash is b8a9908f5d7a8281
'@
    Add-Template $files "spec/design.md" "# Design`n`nGenerated starter design placeholder."
    Add-Template $files "spec/content-plan.md" "# Content plan`n`nThe generated pack is intentionally minimal and data-driven."
    Add-Template $files "spec/engine-gap-analysis.md" "# Engine gap analysis`n`nNo new engine gap is claimed by the generated starter."
    Add-Template $files "spec/balance-plan.md" "# Balance plan`n`nReplace generated values after the first design pass."
    Add-Template $files "spec/android-ux.md" "# Android UX`n`nDefine touch and offline behavior during Gate 1."
    Add-Template $files "spec/nfr.md" "# Non-functional requirements`n`nPreserve deterministic tests and versioned content."
    Add-Template $files "spec/risks.md" "# Risks`n`nGenerated values are scaffolding only and require human review."
    Add-Template $files "spec/traceability.csv" "requirement_id,user_story_id,acceptance_id,design_section,engine_gap_id`nFR-001,US-001,AC-001,design,"

    New-Item -ItemType Directory -Force -Path $stagePath | Out-Null
    foreach ($entry in $files.GetEnumerator()) {
        $relative = $entry.Key.Replace('__SLUG__', $Slug).Replace('__PACKAGE__', $packageName).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
        $destination = Assert-ContainedPath -Path (Join-Path $stagePath $relative) -Container $stagePath
        Write-Utf8NoBom -Path $destination -Content ($entry.Value.Replace('__SLUG__', $Slug).Replace('__PACKAGE__', $packageName))
    }

    Move-Item -LiteralPath $stagePath -Destination $gamePath
    $newline = if ($settingsText.Contains("`r`n")) { "`r`n" } else { "`n" }
    $updatedSettings = $settingsText.TrimEnd("`r", "`n") + $newline + $newline + $includeLine + $newline + $projectLine + $newline
    Write-Utf8NoBom -Path $settingsPath -Content $updatedSettings

    [ordered]@{
        status = "pass"
        slug = $Slug
        module = $modulePath
        path = "games/$Slug"
        files = $files.Count
    } | ConvertTo-Json -Compress
}
catch {
    [ordered]@{
        status = "fail"
        error = $_.Exception.Message
    } | ConvertTo-Json -Compress
    exit 1
}
