wall.costResource=bolt
wall.costAmount=2
wall.maxHealth=20
wall.footprintWidth=1
wall.footprintHeight=1
wall.sellRefundRatio=0.5
wall.displayKey=building.wall
wall.atlasPath=visuals/placeholder.atlas
wall.atlasKey=building.marker
bolt-extractor.costResource=bolt
bolt-extractor.costAmount=2
bolt-extractor.maxHealth=12
bolt-extractor.footprintWidth=1
bolt-extractor.footprintHeight=1
bolt-extractor.sellRefundRatio=0.5
bolt-extractor.displayKey=building.boltExtractor
bolt-extractor.producerRecipeId=bolt-extractor
bolt-extractor.atlasPath=visuals/placeholder.atlas
bolt-extractor.atlasKey=building.marker
belt-straight-east.costResource=bolt
belt-straight-east.costAmount=1
belt-straight-east.maxHealth=1
belt-straight-east.footprintWidth=1
belt-straight-east.footprintHeight=1
belt-straight-east.sellRefundRatio=0.5
belt-straight-east.displayKey=building.beltStraightEast
belt-straight-east.beltGeometry=straight
belt-straight-east.beltDirection=east
belt-straight-east.beltTicksPerCell=1
belt-corner-south.costResource=bolt
belt-corner-south.costAmount=1
belt-corner-south.maxHealth=1
belt-corner-south.footprintWidth=1
belt-corner-south.footprintHeight=1
belt-corner-south.sellRefundRatio=0.5
belt-corner-south.displayKey=building.beltCornerSouth
belt-corner-south.beltGeometry=corner
belt-corner-south.beltDirection=south
belt-corner-south.beltTicksPerCell=1
