easy.healthMult=0.8
easy.countMult=0.9
easy.rewardMult=1.2
easy.goldRateMult=1.2
normal.healthMult=1
normal.countMult=1
normal.rewardMult=1
normal.goldRateMult=1
hard.healthMult=1.3
hard.countMult=1.15
hard.rewardMult=0.9
hard.goldRateMult=0.9
