floor.buildable=true
floor.blocksMovement=false
floor.atlasPath=visuals/placeholder.atlas
floor.atlasKey=tile.floor
wall.buildable=false
wall.blocksMovement=true
wall.atlasPath=visuals/placeholder.atlas
wall.atlasKey=tile.wall
core.buildable=false
core.blocksMovement=false
core.isCore=true
core.atlasPath=visuals/placeholder.atlas
core.atlasKey=tile.core
resource.buildable=false
resource.blocksMovement=false
resource.atlasPath=visuals/placeholder.atlas
resource.atlasKey=tile.resource
