floor.buildable=true
floor.blocksMovement=false
wall.buildable=false
wall.blocksMovement=true
core.buildable=false
core.blocksMovement=false
core.isCore=true
resource.buildable=false
resource.blocksMovement=false
